### ISSUE TITLE
Update to README and files

### ISSUE THREAD

**Issue by morphias2004** [LHardwick-git/Victron-Service#8]
Thanks for writing this code @LHardwick-git :)

As per the details in this thread:

https://community.victronenergy.com/questions/58792/raspberry-pi-3b-heat-temperature.html

Can you please update the README to reflect the changes in newer versions of Venus OS and replace dbus-i2c.py with the updated one from kwindrem?

https://community.victronenergy.com/storage/attachments/27276-dbus-i2cpy.zip

Instead of step 3 being:

create a symlink from /service/dbus-i2c to /opt/victronenergy/dbus-i2c/service
`ln -s /opt/victronenergy/dbus-i2c/service /service/dbus-i2c`

it needs to be

```
mkdir /opt/victronenergy/service/dbus-i2c
cp -r /opt/victronenergy/dbus-i2c/service/* /opt/victronenergy/service/dbus-i2c/
```

In Step 4, additional files need to be made executable:

`chmod a+x dbus-i2c/dbus-i2c.py`
`chmod a+x /service/dbus-i2c/run`

And add a step to comment out the lines related to the 1 Wire Sensor if it isn't in use so an unused sensor is not listed in the devices and displayed in the Pages/Tiles.

![image](https://user-images.githubusercontent.com/68760693/165397091-66574c72-e848-4897-94b8-2643088d471d.png)

![image](https://user-images.githubusercontent.com/68760693/165396987-0d0ade85-dabc-4d4e-b08a-cea9f100f30f.png)

Also, a NOTE to say that this mod is not persistent. If you update Venus OS, you need to do it all again.

It would be great if you could work with @kwindrem to make this part of his Package Manager to automate the install process and also make it auto-reinstall following an update to Venus OS.

Thanks!

**Comment by LHardwick-git** [comment]
I have updated the files and the readme to address these issues.  
I have not been able to test the  changes.
